spring:
  mongodb:
    uri: mongodb+srv://patelmmmut12497:pt80sXmdVxWmG4NN@cluster0.dmalhjx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&tls=true
    database: journaldb
    auto-index-creation : true

server:
  port: 8081
  servlet:
    context-path: /journal



