spring:
  data:
    mongodb:
      uri: mongodb+srv://patelmmmut12497:pt80sXmdVxWmG4NN@cluster0.dmalhjx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&tls=true
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: patelmmmut12497@gmail.com
    password: xxxx xxxx xxxx xxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /journal

weather:
  api:
    key: weather_api_key
