spring:
  data:
    mongodb:
      uri: mongodb+srv://patelmmmut12497:pt80sXmdVxWmG4NN@cluster0.dmalhjx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&tls=true
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal
weather:
  api:
    key: 60084a158f225b3b9c1a617b64f14c0c